/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-29 07:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">      \r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"themes/css/bootstrappage.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- global styles -->\r\n");
      out.write("\t\t<link href=\"themes/css/flexslider.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<link href=\"themes/css/main.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- scripts -->\r\n");
      out.write("\t\t<script src=\"themes/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"bootstrap/js/bootstrap.min.js\"></script>\t\t\t\t\r\n");
      out.write("\t\t<script src=\"themes/js/superfish.js\"></script>\t\r\n");
      out.write("\t\t<script src=\"themes/js/jquery.scrolltotop.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"top-bar\" class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t\t<form method=\"POST\" class=\"search_form\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"input-block-level search-query\" Placeholder=\"Search...\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"span8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"account pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"user-menu\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logReg.jsp\">Login</a></li>\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"wrapper\" class=\"container\">\r\n");
      out.write("\t\t\t<section class=\"navbar main-menu\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-inner main-menu\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\" class=\"logo pull-left\"><img src=\"themes/images/logo.png\" class=\"site_logo\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t<nav id=\"menu\" class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<section  class=\"homepage-slider\" id=\"home-slider\">\r\n");
      out.write("\t\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"themes/images/carousel/banner-1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"themes/images/carousel/banner-2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"intro\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>Sell'n'bye way to the best</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><span>Up to 10000+ customers</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><span>Reliable and efficient service 24/7</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><span>Top Most e-commerce System</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<section class=\"main-content\">\r\n");
      out.write("\t\t\t\t<!-- Main Content -->\r\n");
      out.write("\t\t\t\t<form style = \"text-align: center\" action=\"entry/member/Register\" method=\"POST\" onsubmit=\"return checkPassword()\">\r\n");
      out.write("\t\t\t\t\t<h1>Registration</h1>\r\n");
      out.write("\t\t\t\t\t<label>User Name:</label> <input type=\"text\" name=\"name\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<label>Password:</label> <input type=\"password\" name=\"password\" id = \"pw\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<label>Re-Type Password:</label> <input type=\"password\" name=\"rpassword\" id = \"cpw\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<label>Type:</label> \r\n");
      out.write("\t\t\t\t\t<select name = \"type\">\r\n");
      out.write("\t\t\t\t\t  <option value=\"Seller\">Seller</option>\r\n");
      out.write("\t\t\t\t\t  <option value=\"Buyer\">Buyer</option>\r\n");
      out.write("\t\t\t\t\t</select><br/>\r\n");
      out.write("\t\t\t\t\t<label>Address:</label> <input type=\"text\" name=\"add\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<label>Email id:</label> <input type=\"text\" name=\"mail\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<label>Contact Number:</label> <input type=\"text\" name=\"cno\" required/><br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<section id=\"footer-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Navigation</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./index.html\">Homepage</a></li>  \r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logReg.jsp\">Login</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Others</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Our Clients</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span5\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"logo\"><img src=\"themes/images/logo.png\" class=\"site_logo\" alt=\"\"></p>\r\n");
      out.write("\t\t\t\t\t\t<p>To be successful, you have to use each day as an opportunity to improve, to be better, to get a little bit closer to your goals. It might sound like a lot of workâand with a busy schedule, next to impossible. But the best part is, the more you accomplish, the more youâll want to do, the higher youâll want to reach. So  as long as you have the hunger for success, you will always have the power within you to achieve it.</p>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"social_icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"facebook\" href=\"#\">Facebook</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"twitter\" href=\"#\">Twitter</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"skype\" href=\"#\">Skype</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"vimeo\" href=\"#\">Vimeo</a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<section id=\"copyright\">\r\n");
      out.write("\t\t\t\t<span>Copyright 2019 Sell'N'Bye Company, All right reserved.</span>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script src=\"themes/js/common.js\"></script>\r\n");
      out.write("\t\t<script src=\"themes/js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction checkPassword(){\r\n");
      out.write("\t\t\t\tvar pw =  document.getElementById(\"pw\").value;\r\n");
      out.write("\t\t\t\tvar cpw =  document.getElementById(\"cpw\").value;\r\n");
      out.write("\t\t\t\tif(pw == cpw){\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert(\"Please re type password again!!!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t$('.flexslider').flexslider({\r\n");
      out.write("\t\t\t\t\t\tanimation: \"fade\",\r\n");
      out.write("\t\t\t\t\t\tslideshowSpeed: 4000,\r\n");
      out.write("\t\t\t\t\t\tanimationSpeed: 600,\r\n");
      out.write("\t\t\t\t\t\tcontrolNav: false,\r\n");
      out.write("\t\t\t\t\t\tdirectionNav: true,\r\n");
      out.write("\t\t\t\t\t\tcontrolsContainer: \".flex-container\" // the container that holds the flexslider\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
